apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sagano2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sagano2
    app.kubernetes.io/part-of: sagano2
  name: sagano2
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: sagano2
status:
  loadBalancer: {}
