apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sagano2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jboyer-tenant/sagano2/sagano2@sha256:e5d290fa11b8517ea218ea3cdb7f814b749a670dde0fa19e2984af18255b1bb6
        name: container-image
        resources: {}
status: {}
